### ISSUE TITLE
Question: why two different languages?

### ISSUE THREAD

**Issue by ma763** [SimonEnsemble/mpn_charges#3]
Hello,

Thank you so much for this project, very interesting!

I am not sure if this is the right place to post this, but I have a question: why have you used Julia to build the graphs and not python? It seems odd to me to use two different programming languages for different parts of the project. Is there a way to create the graphs with python?

I'm just trying to understand better if there is a specific reason for using Julia for the graphs.

Thank you very much!
Marta

**Comment by SimonEnsemble** [comment]
> why have you used Julia to build the graphs and not python?

we have the package `Xtals.jl` we're developing to work with crystal structures. see [here](https://github.com/SimonEnsemble/Xtals.jl). we elected to put the bonding rules in there because that is the code we use to work with crystal structures. we are improving the bonding rules and allowing meta data on the nodes and edges. see [here](https://github.com/SimonEnsemble/Xtals.jl/blob/master/src/bonds.jl). it is easy to install once you have Julia. just `]add Xtals`. we have some documentation for bonds too [here](https://simonensemble.github.io/Xtals.jl/dev/bonds/).

as for why Julia in general:
1. I find myself way more productive in Julia than in Python b/c Julia's syntax is much much more intuitive and expressive than in Python, to me, at least. and it's much more fun to program in because of that. (I think my students like Julia too?)
2. Julia is faster than Python.

not sure of a way to infer bonds in Python...
